rule-providers:
  ChinaCompanyIp:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/ChinaCompanyIp.yaml"
    path: ./ACL4SSR/ChinaCompanyIp.yaml
    interval: 86400    

  ChinaIp:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/ChinaIp.yaml"
    path: ./ACL4SSR/ChinaIp.yaml
    interval: 86400    

  ProxyGFWlist:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Providers/ProxyGFWlist.yaml"
    path: ./ACL4SSR/ProxyGFWlist.yaml
    interval: 86400
    
  BanAD:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanAD.yaml"
    path: ./ACL4SSR/BanAD.yaml
    interval: 86400
    
  BanProgramAD:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanProgramAD.yaml"
    path: ./ACL4SSR/BanProgramAD.yaml
    interval: 86400
    
  ChinaDomain:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaDomain.yaml"
    path: ./ACL4SSR/ChinaDomain.yaml
    interval: 86400
    
  LocalAreaNetwork:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/LocalAreaNetwork.yaml"
    path: ./ACL4SSR/LocalAreaNetwork.yaml
    interval: 86400
        
  UnBan:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/UnBan.yaml"
    path: ./ACL4SSR/UnBan.yaml
    interval: 86400
proxy_group:
custom_proxy_group=ğŸ”° èŠ‚ç‚¹é€‰æ‹©`select`[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©`[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢`[]DIRECT
custom_proxy_group=ğŸš€ æ‰‹åŠ¨åˆ‡æ¢`select`.*
custom_proxy_group=â™»ï¸ è‡ªåŠ¨é€‰æ‹©`url-test`(ä¸“çº¿|ä¸­å›½é¦™æ¸¯|ä¸­å›½å°æ¹¾|æ—¥æœ¬å¤§é˜ª|æ—¥æœ¬ä¸œäº¬)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=â›½ Speedtest`select`[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢`[]DIRECT`.*
custom_proxy_group=ğŸ“¬ ç”µæŠ¥æ¶ˆæ¯`select`[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©`[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢`[]ğŸ‡ºğŸ‡² ç¾å›½æ‰‹åŠ¨åˆ‡æ¢
custom_proxy_group=ğŸ“² Discord`select`[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©`[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢`[]ğŸ‡ºğŸ‡² ç¾å›½æ‰‹åŠ¨åˆ‡æ¢
custom_proxy_group=ğŸ¤– Ai`select`[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹`[]ğŸ‡ºğŸ‡² ç¾å›½æ‰‹åŠ¨åˆ‡æ¢
custom_proxy_group=ğŸ¶ TikTok`select`[]ğŸ‡ºğŸ‡² ç¾å›½æ‰‹åŠ¨åˆ‡æ¢`[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹`[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
custom_proxy_group=ğŸ“¹ æ²¹ç®¡è§†é¢‘`select`[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢`(æ—¥æœ¬|ğŸ‡¯ğŸ‡µ|JP|å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan|æ–°åŠ å¡|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore|ç¾å›½|ğŸ‡ºğŸ‡¸|US|ğŸ‡·ğŸ‡º|ä¿„ç½—æ–¯)
custom_proxy_group=ğŸ¥ å¥ˆé£è§†é¢‘`select`[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹`[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹`[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹`[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹`[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹`[]ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹`(æ—¥æœ¬|ğŸ‡¯ğŸ‡µ|JP|å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore|ç¾å›½|ğŸ‡ºğŸ‡¸|US)
custom_proxy_group=âš½ï¸ STAR+å—ç¾`select`[]ğŸŒï¸ å—ç¾æ´²èŠ‚ç‚¹
custom_proxy_group=ğŸ­ Disney`select`(æ—¥æœ¬|ğŸ‡¯ğŸ‡µ|JP|å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore|ç¾å›½|ğŸ‡ºğŸ‡¸|US)
custom_proxy_group=ğŸ AppleTV`select`(æ—¥æœ¬|ğŸ‡¯ğŸ‡µ|JP|å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore|ç¾å›½|ğŸ‡ºğŸ‡¸|US)
custom_proxy_group=ğŸ¥ AmazonPrimeVideo`select`[]ğŸ‡ºğŸ‡² ç¾å›½æ‰‹åŠ¨åˆ‡æ¢`[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹`[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
custom_proxy_group=ğŸ¥ ç¾å›½æµåª’ä½“`select`[]ğŸ‡ºğŸ‡² ç¾å›½æ‰‹åŠ¨åˆ‡æ¢`[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
custom_proxy_group=ğŸ¥ æ—¥æœ¬æµåª’ä½“`select`(æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ—¥|ğŸ‡¯ğŸ‡µ|Japan)
custom_proxy_group=ğŸ¥ è‹±å›½æµåª’ä½“`select`(è‹±å›½|ğŸ‡¬ğŸ‡§|UK|ä¼¦æ•¦)
custom_proxy_group=ğŸ¥ æ¾³æ´²æµåª’ä½“`select`[]ğŸŒ å¤§æ´‹æ´²èŠ‚ç‚¹
custom_proxy_group=ğŸ¥ MyTVSuper`select`[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹`(æ¸¯|HK|Hong Kong|æ·±æ¸¯|)
custom_proxy_group=ğŸ¥ Tvbanywhere`select`(æ¾³é—¨|ğŸ‡²ğŸ‡´|MAC|Macao|æ–°åŠ å¡|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore)
custom_proxy_group=ğŸ¥ ViuTV`select`[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹`[]ğŸ‡²ğŸ‡¾ é©¬æ¥è¥¿äºšèŠ‚ç‚¹`[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
custom_proxy_group=ğŸ¥ çˆ±å¥‡è‰ºå›½é™…`select`[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹`[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹`[]ğŸ‡²ğŸ‡¾ é©¬æ¥è¥¿äºšèŠ‚ç‚¹`[]ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
custom_proxy_group=ğŸ¥ å°æ¹¾æµåª’ä½“`select`[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹`(å°|æ–°åŒ—|å½°åŒ–|ğŸ‡¹ğŸ‡¼|ğŸ‡¨ğŸ‡³|TW|Taiwan)
custom_proxy_group=âš½ DAZN`select`[]ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹`[]ğŸ‡©ğŸ‡ª å¾·å›½èŠ‚ç‚¹`[]ğŸ‡¨ğŸ‡¦ åŠ æ‹¿å¤§èŠ‚ç‚¹
custom_proxy_group=ğŸ F1`select`[]ğŸ‡ºğŸ‡² ç¾å›½æ‰‹åŠ¨åˆ‡æ¢`[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
custom_proxy_group=ğŸ“º å·´å“ˆå§†ç‰¹`select`[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹`[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
custom_proxy_group=ğŸ“º å“”å“©å“”å“©`select`[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹`[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹`[]DIRECT
custom_proxy_group=ğŸ“ºï¸ ä¿„å›½IPTV`select`(è·å…°|ğŸ‡³ğŸ‡±|é˜¿å§†æ–¯ç‰¹ä¸¹|å¾·å›½|DE|æ³¢å…°|ä¿„ç½—æ–¯|ğŸ‡·ğŸ‡º|æ³•å›½|è‹±å›½|è‹±|GBR|åœŸè€³å…¶)
custom_proxy_group=ğŸ“ºï¸ æ¬§æ´²IPTV`select`[]ğŸ’¶ æ¬§æ´²èŠ‚ç‚¹
custom_proxy_group=ğŸ“ºï¸ ç¾åœ‹IPTV`select`[]ğŸ‡ºğŸ‡² ç¾å›½æ‰‹åŠ¨åˆ‡æ¢`[]ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹
custom_proxy_group=ğŸ“ºï¸ åŠ æ‹¿å¤§IPTV`select`(ğŸ‡¨ğŸ‡¦|Ca|åŠ æ‹¿å¤§)
custom_proxy_group=âš½ï¸ æ˜Ÿé©¬IPTV`select`(é©¬æ¥è¥¿äºš|ğŸ‡²ğŸ‡¾|MYS|æ–°åŠ å¡|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore)
custom_proxy_group=ğŸ¬ PLEX`select`[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©`[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢`[]DIRECT
custom_proxy_group=ğŸ¬ EMBY`select`[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©`[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢`(æ¸¯|HK|Hong Kong)
custom_proxy_group=ğŸ‘¨â€ğŸ’» GitHub`select`[]ğŸ“¥ ä¸‹è½½ä¸“ç”¨
custom_proxy_group=ğŸš¢ Docker`select`[]ğŸ“¥ ä¸‹è½½ä¸“ç”¨
custom_proxy_group=ğŸ“¢ è°·æ­ŒFCM`select`[]DIRECT`[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
custom_proxy_group=ğŸ“¢ è°·æ­Œ`select`[]DIRECT``[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
custom_proxy_group=â“‚ï¸ å¾®è½¯Bing`select`[]DIRECT`[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©`[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢`[]ğŸ‡ºğŸ‡² ç¾å›½æ‰‹åŠ¨åˆ‡æ¢
custom_proxy_group=â“‚ï¸ å¾®è½¯äº‘ç›˜`select`[]DIRECT`[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©`[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢`[]ğŸ‡ºğŸ‡² ç¾å›½æ‰‹åŠ¨åˆ‡æ¢
custom_proxy_group=â“‚ï¸ å¾®è½¯æœåŠ¡`select`[]DIRECT`[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©`[]ğŸ‡ºğŸ‡² ç¾å›½æ‰‹åŠ¨åˆ‡æ¢
custom_proxy_group=ğŸ è‹¹æœæœåŠ¡`select`[]DIRECT`[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©`[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
custom_proxy_group=ğŸ® æ¸¸æˆå¹³å°`select`[]DIRECT`[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢`(æ¸¸æˆ)
custom_proxy_group=ğŸ¯ å…¨çƒç›´è¿`select`[]DIRECT`[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢`[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©
custom_proxy_group=ğŸ›‘ å¹¿å‘Šæ‹¦æˆª`select`[]REJECT`[]DIRECT
custom_proxy_group=ğŸƒ åº”ç”¨å‡€åŒ–`select`[]REJECT`[]DIRECT
custom_proxy_group=ğŸŸ æ¼ç½‘ä¹‹é±¼`select`[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©`[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢`[]DIRECT
custom_proxy_group=ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹`url-test`(æ¸¯|ğŸ‡­ğŸ‡°|HK|Hong Kong)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹`url-test`(æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ—¥|ğŸ‡¯ğŸ‡µ|Japan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹`url-test`(ç¾å›½|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|ğŸ‡ºğŸ‡¸|USA|United States)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=ğŸ‡¬ğŸ‡§ è‹±å›½èŠ‚ç‚¹`url-test`(è‹±å›½|è‹±|ğŸ‡¬ğŸ‡§|GBR)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹`url-test`(å°|æ–°åŒ—|å½°åŒ–|ğŸ‡¨ğŸ‡³|TW|Taiwan)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹`url-test`(å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=ğŸ‡¨ğŸ‡¦ åŠ æ‹¿å¤§èŠ‚ç‚¹`url-test`(ğŸ‡¨ğŸ‡¦|Ca|åŠ æ‹¿å¤§)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=ğŸ‡©ğŸ‡ª å¾·å›½èŠ‚ç‚¹`url-test`(ğŸ‡©ğŸ‡ª|å¾·å›½)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹`url-test`(ğŸ‡°ğŸ‡·|Korea|KOR|é¦–å°”|éŸ©|éŸ“)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=ğŸ‡²ğŸ‡¾ é©¬æ¥è¥¿äºšèŠ‚ç‚¹`url-test`(é©¬æ¥è¥¿äºš|ğŸ‡²ğŸ‡¾|MYS)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=ğŸ‡»ğŸ‡³ è¶Šå—èŠ‚ç‚¹`url-test`(è¶Šå—|VN|ğŸ‡»ğŸ‡³)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=ğŸ‡µğŸ‡­ è²å¾‹å®¾èŠ‚ç‚¹`url-test`(è²å¾‹å®¾|ğŸ‡µğŸ‡­)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=ğŸ‡ºğŸ‡² ç¾å›½æ‰‹åŠ¨åˆ‡æ¢`select`(ç¾å›½|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|ğŸ‡ºğŸ‡¸|US|United States)
custom_proxy_group=ğŸŒ å¤§æ´‹æ´²èŠ‚ç‚¹`select`(æ¾³å¤§åˆ©äºš|ğŸ‡¦ğŸ‡º|AU|æ–°è¥¿å…°|New|ğŸ‡³ğŸ‡¿|NZL)
custom_proxy_group=ğŸŒï¸ å—ç¾æ´²èŠ‚ç‚¹`select`(å·´è¥¿|ğŸ‡§ğŸ‡·|æ™ºåˆ©|ç§˜é²|é˜¿æ ¹å»·|ARG|ğŸ‡¦ğŸ‡·|ä¹Œæ‹‰åœ­|å·´æ‹‰åœ­|å„ç“œå¤šå°”|å“¥ä¼¦æ¯”äºš|å§”å†…ç‘æ‹‰)
custom_proxy_group=ğŸ’¶ æ¬§æ´²èŠ‚ç‚¹`select`(è·å…°|ğŸ‡³ğŸ‡±|é˜¿å§†æ–¯ç‰¹ä¸¹|å¾·å›½|DE|æ³¢å…°|ä¿„ç½—æ–¯|ğŸ‡·ğŸ‡º|æ³•å›½|è‹±å›½|è‹±|GBR|åœŸè€³å…¶)
custom_proxy_group=ğŸ“¥ ä¸‹è½½ä¸“ç”¨`url-test`(éŸ©å›½-å¹¿ä¸œä¸“çº¿|æ—¥æœ¬-å¹¿ä¸œä¸“çº¿|å°æ¹¾-å¹¿ä¸œä¸“çº¿)`http://www.gstatic.com/generate_204`300,,50
;è®¾ç½®åˆ†ç»„æ ‡å¿—ä½
